name: GISAID fetch and ingest

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # "At 03:00 (05:00 CET) on every day-of-week from Monday through Friday."
    - cron:  '7 13 * * *'

  # Manually triggered using `./bin/trigger gisaid/fetch-and-ingest`
  repository_dispatch:
    types:
      - gisaid/fetch-and-ingest
      - fetch-and-ingest

  # Manually triggered using GitHub's UI
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: setup
      run: ./bin/setup-github-workflow

    - name: ingest
      run: |
        ./bin/write-envdir env.d \
          AWS_DEFAULT_REGION \
          GISAID_API_ENDPOINT \
          GISAID_USERNAME_AND_PASSWORD \
          GITHUB_REF \
          GITHUB_RUN_ID \
          SLACK_TOKEN \
          SLACK_CHANNELS \
          PAT_GITHUB_DISPATCH

        nextstrain build \
          --aws-batch \
          --no-download \
          --image nextstrain/ncov-ingest \
          --cpus 16 \
          --memory 31GiB \
          --exec env \
          . \
            envdir env.d ingest-gisaid --fetch
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GISAID_API_ENDPOINT: ${{ secrets.GISAID_API_ENDPOINT }}
        GISAID_USERNAME_AND_PASSWORD: ${{ secrets.GISAID_USERNAME_AND_PASSWORD }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNELS: ncov-gisaid-updates
        PAT_GITHUB_DISPATCH: ${{ secrets.PAT_GITHUB_DISPATCH }}
